// Generated by tools/generate_runtime_math_tables.py; no ROM input.
#include "System/RuntimeMathTables.h"

extern const RuntimeMathTables data_020e6abc = {
    // log2(1) and log2(1.5), split at 24 significand bits.
    {0.0, 0.5849624872207642},
    {1.0, 1.5},
    {0.0, 1.350039202129749e-08},
    // High binary64 words of n*pi/2, n=1..32.
    {
        0x3ff921fb, 0x400921fb, 0x4012d97c, 0x401921fb, 0x401f6a7a, 0x4022d97c, 0x4025fdbb, 0x402921fb,
        0x402c463a, 0x402f6a7a, 0x4031475c, 0x4032d97c, 0x40346b9c, 0x4035fdbb, 0x40378fdb, 0x403921fb,
        0x403ab41b, 0x403c463a, 0x403dd85a, 0x403f6a7a, 0x40407e4c, 0x4041475c, 0x4042106c, 0x4042d97c,
        0x4043a28c, 0x40446b9c, 0x404534ac, 0x4045fdbb, 0x4046c6cb, 0x40478fdb, 0x404858eb, 0x404921fb,
    },
    // Base-2^24 fractional digits of 2/pi.
    {
        0xa2f983, 0x6e4e44, 0x1529fc, 0x2757d1, 0xf534dd, 0xc0db62,
        0x95993c, 0x439041, 0xfe5163, 0xabdebb, 0xc561b7, 0x246e3a,
        0x424dd2, 0xe00649, 0x2eea09, 0xd1921c, 0xfe1deb, 0x1cb129,
        0xa73ee8, 0x8235f5, 0x2ebb44, 0x84e99c, 0x7026b4, 0x5f7e41,
        0x3991d6, 0x398353, 0x39f49c, 0x845f8b, 0xbdf928, 0x3b1ff8,
        0x97ffde, 0x05980f, 0xef2f11, 0x8b5a0a, 0x6d1f6d, 0x367ecf,
        0x27cb09, 0xb74f46, 0x3f669e, 0x5fea2d, 0x7527ba, 0xc7ebe5,
        0xf17b3d, 0x0739f7, 0x8a5292, 0xea6bfb, 0x5fb11f, 0x8d5d08,
        0x560330, 0x46fc7b, 0x6babf0, 0xcfbc20, 0x9af436, 0x1da9e3,
        0x91615e, 0xe61b08, 0x659985, 0x5f14a0, 0x68408d, 0xffd880,
        0x4d7327, 0x310606, 0x1556ca, 0x73a8c9, 0x60e27b, 0xc08c6b,
    },
    // Initial convolution term counts indexed by requested precision.
    {2, 3, 4, 6},
    // Successive 24-significand-bit pieces of pi/2.
    {
        1.570796251296997,
        7.549789415861596e-08,
        5.390302529957765e-15,
        3.282003415807913e-22,
        1.270655753080676e-29,
        1.2293330898111133e-36,
        2.7337005381646456e-44,
        2.1674168387780482e-51,
    },
};
