"""Regenerate the two arctangent tables from their mathematical definitions."""
from pathlib import Path
import argparse
import math


def render():
    lines = ['// Generated by tools/generate_atan_tables.py; no ROM input is used.',
             '#include "System/Matrix.h"', '',
             '// 129 samples of atan(i / 128), rounded to nearest positive integer.',
             '// The final zero is storage padding matching the original four-byte boundary.']
    for name, scale in [('data_020ed450', 4096), ('data_020ed554', 65536 / (2 * math.pi))]:
        values = [int(math.atan(i / 128) * scale + 0.5) for i in range(129)] + [0]
        lines += ['', f'extern "C" const int16_t {name}[130] = {{']
        for start in range(0, len(values), 10):
            lines.append('    ' + ', '.join(map(str, values[start:start + 10])) + ',')
        lines.append('};')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='check committed source without writing')
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / 'src/System/FixedPointAtanTables.cpp'
    generated = render()
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('Arctangent table source is stale')
        print('Arctangent table source matches the mathematical generator')
    else:
        target.write_text(generated)


if __name__ == '__main__':
    main()
