"""Generate the q12 sine/cosine lookup table used by fixed-point graphics math."""
import argparse
import math
from pathlib import Path


def values():
    values = []
    for index in range(4096):
        phase = 2.0 * math.pi * index / 4096
        values.extend((round(math.sin(phase) * 4096),
                       round(math.cos(phase) * 4096)))
    return values


def render(symbol, entries, phase_start):
    rows = ["    " + ", ".join(str(value) for value in entries[i:i + 16]) + ","
            for i in range(0, len(entries), 16)]
    return ('// Generated by tools/generate_fixed_point_sincos_table.py; '
            f'q12 sine/cosine values from phase pair {phase_start}.\n'
            '#include "Graphics/Vector.h"\n\n'
            f'extern const fix16_t {symbol}[{len(entries)}] = {{\n'
            + '\n'.join(rows) + '\n};\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1] / 'src/Graphics'
    all_values = values()
    expected = {
        root / 'FixedPointSinCosTable.cpp': render('data_020e9450', all_values[:768], 0),
        root / 'FixedPointSinCosTableContinuation.cpp': render(
            'data_020e9a50', all_values[768:], 384),
    }
    if args.check:
        for path, source in expected.items():
            if path.read_text() != source:
                raise SystemExit(f'sine/cosine table source differs from generated values: {path.name}')
        print('Fixed-point sine/cosine table source verified')
    else:
        for path, source in expected.items():
            path.write_text(source)


if __name__ == '__main__':
    main()
