"""Generate the file-cache reflected CRC-32 table from its polynomial."""
import argparse
from pathlib import Path


def render():
    values = []
    for byte in range(256):
        crc = byte
        for _ in range(8):
            crc = (crc >> 1) ^ (0xedb88320 if crc & 1 else 0)
        values.append(crc)
    rows = ["    " + ", ".join(f"0x{value:08x}u" for value in values[i:i + 8]) + ","
            for i in range(0, 256, 8)]
    return ('// Generated by tools/generate_crc32_table.py; reflected polynomial 0xedb88320.\n'
            'extern "C" const unsigned int data_020ee278[256] = {\n'
            + '\n'.join(rows) + '\n};\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = Path(__file__).resolve().parents[1] / 'src/Filesystem/FileCacheCRCTable.cpp'
    expected = render()
    if args.check:
        if path.read_text() != expected:
            raise SystemExit('CRC table source differs from polynomial-generated values')
        print('CRC-32 table source verified')
    else:
        path.write_text(expected)


if __name__ == '__main__':
    main()
