"""Regenerate shared runtime math tables without reading any ROM input."""
import argparse
from decimal import Decimal, localcontext
import math
from pathlib import Path
import struct


def pi():
    # Chudnovsky series; 50 terms exceed the 540 decimal digits used below.
    multiplier, linear, power, k = 1, 13591409, 1, 6
    total = Decimal(linear)
    for i in range(1, 50):
        multiplier = multiplier * (k ** 3 - 16 * k) // (i ** 3)
        linear += 545140134
        power *= -262537412640768000
        total += Decimal(multiplier * linear) / power
        k += 12
    return 426880 * Decimal(10005).sqrt() / total


def leading_piece(value):
    exponent = math.frexp(float(value))[1] - 1
    scale = Decimal(2) ** (23 - exponent)
    return Decimal(int(value * scale)) / scale


def render():
    with localcontext() as context:
        context.prec = 540
        circle = pi()
        logarithm = Decimal('1.5').ln() / Decimal(2).ln()
        high = leading_piece(logarithm)
        high_words = [struct.unpack('<II', struct.pack('<d', float(circle * n / 2)))[1]
                      for n in range(1, 33)]
        inverse = 2 / circle
        inverse_digits = []
        for _ in range(66):
            inverse *= 1 << 24
            digit = int(inverse)
            inverse_digits.append(digit)
            inverse -= digit
        remainder = circle / 2
        pieces = []
        for _ in range(8):
            piece = leading_piece(remainder)
            pieces.append(float(piece))
            remainder -= piece
        lines = ['// Generated by tools/generate_runtime_math_tables.py; no ROM input.',
                 '#include "System/RuntimeMathTables.h"', '',
                 'extern const RuntimeMathTables data_020e6abc = {',
                 '    // log2(1) and log2(1.5), split at 24 significand bits.',
                 f'    {{0.0, {float(high)!r}}},',
                 '    {1.0, 1.5},',
                 f'    {{0.0, {float(logarithm - high)!r}}},',
                 '    // High binary64 words of n*pi/2, n=1..32.', '    {']
        for start in range(0, 32, 8):
            lines.append('        ' + ', '.join(f'0x{x:08x}' for x in high_words[start:start + 8]) + ',')
        lines += ['    },', '    // Base-2^24 fractional digits of 2/pi.', '    {']
        for start in range(0, 66, 6):
            lines.append('        ' + ', '.join(f'0x{x:06x}' for x in inverse_digits[start:start + 6]) + ',')
        lines += ['    },', '    // Initial convolution term counts indexed by requested precision.',
                  '    {2, 3, 4, 6},', '    // Successive 24-significand-bit pieces of pi/2.', '    {']
        for value in pieces:
            lines.append(f'        {value!r},')
        lines += ['    },', '};']
        return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = Path(__file__).resolve().parents[1] / 'src/System/RuntimeMathTables.cpp'
    source = render()
    if args.check:
        if path.read_text() != source:
            raise SystemExit('Runtime math table source is stale')
        print('Runtime math table source matches its mathematical generator')
    else:
        path.write_text(source)


if __name__ == '__main__':
    main()
